### ISSUE TITLE
Sort out flexbox delta btwn FF + Chrome in `How it Works` section

### ISSUE THREAD

**Issue by arisaves** [monetcap/credit-by-monet#1]
This bug seems to deal primarily with the image scaling in flexbox -- ensure that firefox renders the same way that chrome does; does explicitly setting an image size help get around this? if so, what are the drawbacks of doing that?

**Comment by Bjorkbat** [comment]
Alright, took care of it.

For future reference, both the `h4` and the `img` tags within class="foo" (I'm changing that name) had their width set to 100%.  Normally, they would both take up the full width of their container and siblings would just get rendered above or below.

With flex, things can change.

With firefox they basically behave like elements with equal flex-grow properties.  With Chrome, eh, I don't know what's going on honestly.

Simple fix, I changed the width to both to 50%.  There's no longer any difference betwen webkit or firefox.
