### ISSUE TITLE
Need a hand with offcanvas (changes in development branch)

### ISSUE THREAD

**Issue by arisaves** [monetcap/credit-by-monet#3]
Hey -- I had meant to style off-canvas but between calls and proposals and DS, I keep getting pulled. I was looking to style it the way I had styled it for monetcap.com but only got as far as the logo bit: https://github.com/monetcap/uikit-react-boilerplate/blob/master/src/stylesheets/components/mixins/_navbar.scss

Attaching a screenshot as well. I was trying to use v-vk-scroll but not quite succeeding and I tried to add the "flipped" attribute as specified in the vuikit docs but it didn't work on my offcanvas menu for some reason.

I've updated the link text in my commit to represent where I need these to go and here's an image of the monetcap menu for style reference:
<img width="352" alt="Screen Shot 2019-04-10 at 1 07 39 PM" src="https://user-images.githubusercontent.com/886231/55906838-66d37e00-5b92-11e9-811e-0413621bf611.png">

Styling is less important and I can add it later; I just want to make sure I'm showing the forms I need to and scrolling to the `how it works` and `testimonials` divs.

Sry, my vue is still in need of conditioning and my code will need to be refactored later.

**Comment by arisaves** [comment]
Looks really good! I can't sort out why the scroll won't work on the divs i'm IDing though (i'm trying it locally) -- I don't know if its div placement or something else; I can navigate to them directly in the address bar though.

to reproduce: add an id to the `how it works` section wrapper and then try to assign it as the href attribute.

**Comment by Bjorkbat** [comment]
Navigation works.  In order for `v-vk-scroll` to work properly with an a tag the innerHTML of the a tag must be wrapped in another element.

So I wrapped the text inside the a tags with span tags
